name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    container:
        image: python:2.7.18-buster # https://github.com/actions/setup-python/issues/672

    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'cmip6hack'
        reponame: 'cmip6hack.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged