name: Build static site
on: 

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    name: Build Vue
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: set up conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
    - name: Build-Vue 
      run: |
        npm install
        npm run build 
    